package br.com.medshare.notificacao;

public enum TipoNotificacao {
    DOACAO_PRE_VALIDADA,
    DOACAO_EM_ANALISE,
    DOACAO_RECUSADA,
    DOACAO_RECEBIDA,
    DOACAO_DISPONIVEL,
    NOVA_FOTO_SOLICITADA,
    LEMBRETE_DE_ENTREGA,
    AGENDAMENTO_CANCELADO,
    OFERTA_RECEBIDA,
    OFERTA_EXPIRADA,
    RESERVA_CRIADA,
    RESERVA_EXPIRANDO,
    RESERVA_EXPIRADA,
    ENTREGA_NEGADA,
    ENTREGA_CONCLUIDA,
    CADUNICO_CONFIRMADO,
    CENTRAL_ATRASADA
}
