/** Como cada evento do histórico (RN06) aparece para quem lê. Um lugar só. */
export const NOME_DO_EVENTO: Record<string, string> = {
  CADASTRO: 'Cadastro',
  PRE_VALIDACAO: 'Pré-validação',
  ENVIO_PARA_CENTRAL: 'Enviada para a central',
  DECISAO_DA_CENTRAL: 'Decisão da central',
  NOVA_FOTO_SOLICITADA: 'Nova foto solicitada',
  NOVA_FOTO_ENVIADA: 'Nova foto enviada',
  AGENDAMENTO: 'Agendamento',
  REAGENDAMENTO: 'Reagendamento',
  RECEBIMENTO: 'Recebimento',
  CORRECAO_DE_DADOS: 'Correção no balcão',
  VALIDACAO: 'Conferência do farmacêutico',
  DISPONIBILIZACAO: 'Disponibilizada',
  TRANSFERENCIA: 'Transferência entre farmácias',
  OFERTA: 'Oferecida a quem precisa',
  RESERVA: 'Reservada',
  EXPIRACAO_DE_RESERVA: 'Reserva expirada',
  CANCELAMENTO_DE_RESERVA: 'Reserva cancelada',
  ENTREGA: 'Entrega',
  RECUSA: 'Recusa',
  CANCELAMENTO: 'Cancelamento',
  REJEICAO: 'Rejeição',
  DESCARTE: 'Descarte',
}
